---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: false
configure_osx: true

configure_dock: True
dockitems_to_remove:
  - Launchpad
  - Safari
  - Messages
  - Mail
  - Maps
  - Photos
  - FaceTime
  - Calendar
  - Contacts
  - Reminders
  - Notes
  - TV
  - Music
  - Podcasts
  - 'App Store'
remove_spacers: true
dockitems_to_persist:
 - name: iTerm
   path: "/Applications/iTerm.app/"
 - name: "Google Chrome"
   path: "/Applications/Google Chrome.app/"
configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: git@github.com:kalopilato/dotfiles.git
dotfiles_repo_version: main
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/projects/dotfiles
dotfiles_files:
  - .osx
  - .gitconfig
  - .zshrc

homebrew_installed_packages:
  # - autoconf
  - autojump
  # - bash-completion
  # - doxygen
  # - gettext
  # - gifsicle
  # - git
  - gh
  # - go
  # - gpg
  - httpie
  # - iperf
  # - libevent
  # - sqlite
  # - mcrypt
  # - nmap
  - node
  - nvm
  # - php
  # - ssh-copy-id
  # - cowsay
  # - readline
  # - openssl
  - pv
  - wget
  - wrk
  - zsh-syntax-highlighting
  - zsh-autosuggestions

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - alfred
  - chromedriver
  - dropbox
  - firefox
  - google-chrome
  - licecap
  - slack

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
